language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly

install:
  - git fetch --unshallow
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Chemfiles")'

script:
  - julia --check-bounds=yes --inline=no -e 'Pkg.test("Chemfiles"; coverage=true)'
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_JULIA_VERSION}" == "0.6" ]]; then
        julia -e 'cd(Pkg.dir("Chemfiles")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
        ./build-docs.sh
        cd ${TRAVIS_BUILD_DIR}
    fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        branch: master
        condition: "${TRAVIS_OS_NAME} == linux && ${TRAVIS_JULIA_VERSION} == 0.6"
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
    on:
        tags: true
        condition: "${TRAVIS_OS_NAME} == linux && ${TRAVIS_JULIA_VERSION} == 0.6"
