environment:
  matrix:
      - JULIA_VERSION: "v0.4"
        ARCH: x86
        JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.4/julia-0.4.1-win32.exe"
      - JULIA_VERSION: "v0.4"
        ARCH: x64
        JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.4/julia-0.4.1-win64.exe"
      - JULIA_VERSION: "v0.5"
        ARCH: x86
        JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x86/julia-latest-win32.exe"
      - JULIA_VERSION: "v0.5"
        ARCH: x64
        JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

install:
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"
  - ps: (new-object net.webclient).DownloadFile(
              $env:JULIA_URL,
              "C:\projects\julia-installer.exe"
        )
  - C:\projects\julia-installer.exe /S /D=C:\projects\julia

build_script:
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.clone(pwd(), \"Chemfiles\"); Pkg.build(\"Chemfiles\")"

test_script:
  - C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"Chemfiles\")"
