name = "Chemfiles"
uuid = "b6293618-cad8-11e8-2259-85924205ccb0"
authors = ["Guillaume Fraux <guillaume.fraux@chimie-paristech.fr>"]
version = "0.8.1"

[compat]
julia = "1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
