name = "Chemfiles"
uuid = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
authors = ["Guillaume Fraux <guillaume.fraux@chimie-paristech.fr>"]
version = "0.9.3"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Chemfiles_jll = "78a364fa-1a3c-552a-b4bb-8fa0f9c1fcca"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
BinaryProvider = "0.5.8"
Chemfiles_jll = "= 0.9.3"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
