name = "Chemfiles"
uuid = "46823bd8-5fb3-5f92-9aa0-96921f3dd015"
authors = ["Guillaume Fraux <guillaume.fraux@epfl.ch>"]
version = "0.10.41"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
Chemfiles_jll = "78a364fa-1a3c-552a-b4bb-8fa0f9c1fcca"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
AtomsBase = "0.5"
AtomsBaseTesting = "0.4"
Chemfiles_jll = "= 0.10.4"
DocStringExtensions = "0.8.3, 0.9"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1.6"

[extras]
AtomsBaseTesting = "ed7c10db-df7e-4efa-a7be-4f4190f7f227"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AtomsBaseTesting", "Test"]
